### ISSUE TITLE
New `doped` version is needed

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [SMTG-Bham/ShakeNBreak#68]
The `pyproject.toml` for `shakenbreak` 3.3.1 indicates that it relies on `doped>=2.3.1`, but the most recent PyPI release of `doped` is 2.3.0.

**Comment by kavanase** [comment]
Hi Andrew, thanks very much for flagging this!
Yes so there was a co-dependent update for both `ShakeNBreak` and `doped` (should be the last of these), so we were releasing new versions of them both concurrently, however the test & release workflow for `doped` failed due to a breaking change in the version of `pymatgen` just released today (`2024.3.1`) – something unexpected always crops up when you go to release... 😅 

This is fixed now (in `doped` `v2.3.2`) which has just been released.

**Comment by Andrew-S-Rosen** [comment]
Great!! Wanted to make sure it was on your radar, but I'm not at all surprised that it was. Thanks for your nice work on this!

**Comment by Andrew-S-Rosen** [comment]
Opened a PR here: https://github.com/SMTG-Bham/doped/pull/75.

**Comment by kavanase** [comment]
👍  release coming soon!

**Comment by Andrew-S-Rosen** [comment]
I swear, how do I keep posting in the wrong issue. This time I posted in an old issue report 🤣 I'm hopeless.

Thank you 🙏

**Comment by kavanase** [comment]
No problem haha, new `ShakeNBreak` and `doped` both released now!

**Comment by Andrew-S-Rosen** [comment]
WOOOOO!!!!
