### ISSUE TITLE
An error occurs when `pip install .`

### ISSUE THREAD

**Issue by zhoufy20** [SMTG-Bham/ShakeNBreak#78]
Dear developers of ShakeNBreak:

How can I solve this problem when `pip install -e .`? Thanks a lot!  

Your response and assistance in this matter would be greatly appreciated. Thank you for your attention to this matter.

![image](https://github.com/user-attachments/assets/196bfe0c-6b27-4c73-bea9-c82b94421ad9)

Note: I just run `conda install -c conda-forge shakenbreak`, and it is ok! But pip not.

**Comment by kavanase** [comment]
Hi @zhoufy20,
Yes I noticed this issue recently as well. It's come up because `phonopy` has changed their installation procedure since `v2.26`, which now causes issues with editable `pip install` for some reason. This can be fixed by first installing `phonopy` (with `conda` or (I think) `pip install`), and then doing the editable SnB install.
I'll try figure out if this can be automatically avoided somehow for users who want to `pip install -e .`, otherwise will update the docs/readme.

**Comment by zhoufy20** [comment]
How about this? I am trying to reproduce this interesting work.
![image](https://github.com/user-attachments/assets/72333848-07cf-4eb2-b651-da220a812892)

```
from pymatgen.core.structure import Structure
from doped.generation import DefectsGenerator

bulk = Structure.from_file("CdTe_Bulk_Primitive_POSCAR")  # CdTe
defect_gen = DefectsGenerator(bulk)

from shakenbreak.input import Distortions
# In order to determine the number of the defect nearest neighbours to distort (based on the change 
# in valence electrons mentioned above), SnB uses the oxidation states of atoms in our material:
# If not specified, the code will guess these, otherwise you can specify as such:
# oxidation_states = {"Cd": +2, "Te": -2}  # specify atom oxidation states

# Create an instance of Distortion class with the defects and distortion parameters
# If distortion parameters are not specified, the default values are used
Dist = Distortions(defect_gen)  # initialise with doped DefectsGenerator

**Comment by kavanase** [comment]
For that I'm not sure, I've never seen it. `h5py` is not a direct dependency of `ShakeNBreak`, but indirect through `hiphive`.
I would check your versions of `hiphive` and `h5py` (`pip show hiphive`), then update (`pip install -U h5py hiphive`), restart your notebook and then see if that fixes it?
Otherwise googling this specific error message.

If you get it solved, can you let us know what fixed it please?

**Comment by zhoufy20** [comment]
```
when I run the command of `pip show hiphive`
Name: hiphive
Version: 1.3.1
Summary: High-order force constants for the masses
Home-page: http://hiphive.materialsmodeling.org/
Author: 
Author-email:
License:
Location: /home/deroot/miniconda3/envs/snb/lib/python3.10/site-packages
Requires: ase, h5py, numba, numpy, pandas, scikit-learn, scipy, spglib, sympy, trainstation
Required-by: shakenbreak
``` 

and run `pip install -U h5py hiphive` is OK! Thanks a lot!
